#!/bin/sh

./autogen.sh
./my-configure mingw
make clean
make -j4
cp src/MITZEband.exe .
if [ -n "$1" ]
then
    file=MITZEband-"$1".zip
else
    file=MITZEband-"$(git describe)".zip
fi

rm $file
find ./lib -name Makefile -prune -o -name .deps -prune -o -print | zip $file -@
zip $file MITZEband.exe readme.txt
